version: '3'

services:
  
  # Microservices front-end
  uchuva_index:    
    image:
      steven0414/uchuva_index
    restart:
      always
    volumes:
      - uchuva:/app
    ports:
      - "3000:3000"
    links:
      - rabbit
    environment:
      SHARE: /app
      CONDOR_URL: http://htcondor:8080/
      CONDOR_JOB_OWNER: uchuva
      BMANAGER: 3
      QUEUE : 'amqp://user:password@rabbit'
    labels:
      kompose.service.type: nodeport
      
  uchuva_admin:    
    image:
      steven0414/uchuva_admin
    restart:
      always
    volumes:
      - uchuva:/app
    ports:
      - "3000:3000"
    links:
      - rabbit
    environment:
      SHARE: /app
      CONDOR_URL: http://htcondor:8080/
      CONDOR_JOB_OWNER: uchuva
      BMANAGER: 3
      QUEUE : 'amqp://user:password@rabbit'
    labels:
      kompose.service.type: nodeport
      
  uchuva_builds:    
    image:
      steven0414/uchuva_builds
    restart:
      always
    volumes:
      - uchuva:/app
    ports:
      - "3000:3000"
    links:
      - rabbit
    environment:
      SHARE: /app
      CONDOR_URL: http://htcondor:8080/
      CONDOR_JOB_OWNER: uchuva
      BMANAGER: 3
      QUEUE : 'amqp://user:password@rabbit'
    labels:
      kompose.service.type: nodeport
      
  uchuva_consola:    
    image:
      steven0414/uchuva_consola
    restart:
      always
    volumes:
      - uchuva:/app
    ports:
      - "3000:3000"
    links:
      - rabbit
    environment:
      SHARE: /app
      CONDOR_URL: http://htcondor:8080/
      CONDOR_JOB_OWNER: uchuva
      BMANAGER: 3
      QUEUE : 'amqp://user:password@rabbit'
    labels:
      kompose.service.type: nodeport
      
  uchuva_dag:    
    image:
      steven0414/uchuva_dag
    restart:
      always
    volumes:
      - uchuva:/app
    ports:
      - "3000:3000"
    links:
      - rabbit
    environment:
      SHARE: /app
      CONDOR_URL: http://htcondor:8080/
      CONDOR_JOB_OWNER: uchuva
      BMANAGER: 3
      QUEUE : 'amqp://user:password@rabbit'
    labels:
      kompose.service.type: nodeport
      
  uchuva_ejecuciones:    
    image:
      steven0414/uchuva_ejecuciones
    restart:
      always
    volumes:
      - uchuva:/app
    ports:
      - "3000:3000"
    links:
      - rabbit
    environment:
      SHARE: /app
      CONDOR_URL: http://htcondor:8080/
      CONDOR_JOB_OWNER: uchuva
      BMANAGER: 3
      QUEUE : 'amqp://user:password@rabbit'
    labels:
      kompose.service.type: nodeport
  
  uchuva_programas:    
    image:
      steven0414/uchuva_programas
    restart:
      always
    volumes:
      - uchuva:/app
    ports:
      - "3000:3000"
    links:
      - rabbit
    environment:
      SHARE: /app
      CONDOR_URL: http://htcondor:8080/
      CONDOR_JOB_OWNER: uchuva
      BMANAGER: 3
      QUEUE : 'amqp://user:password@rabbit'
    labels:
      kompose.service.type: nodeport
  
  uchuva_run:    
    image:
      steven0414/uchuva_run
    restart:
      always
    volumes:
      - uchuva:/app
    ports:
      - "3000:3000"
    links:
      - rabbit
    environment:
      SHARE: /app
      CONDOR_URL: http://htcondor:8080/
      CONDOR_JOB_OWNER: uchuva
      BMANAGER: 3
      QUEUE : 'amqp://user:password@rabbit'
    labels:
      kompose.service.type: nodeport
      
  uchuva_vfs:    
    image:
      steven0414/uchuva_vfs
    restart:
      always
    volumes:
      - uchuva:/app
    ports:
      - "3000:3000"
    links:
      - rabbit
    environment:
      SHARE: /app
      CONDOR_URL: http://htcondor:8080/
      CONDOR_JOB_OWNER: uchuva
      BMANAGER: 3
      QUEUE : 'amqp://user:password@rabbit'
    labels:
      kompose.service.type: nodeport
  
  # Worker
  uchuvaworker:
    image: steven0414/uchuva
    command:
      npm run worker
    volumes:
      - uchuva:/app
    expose:
      - "3000"
    links:
      - rabbit
    restart:
      always
    environment:
      SHARE: /app
      CONDOR_URL: http://htcondor:8080/
      CONDOR_JOB_OWNER: uchuva
      BMANAGER: 3
      QUEUE : 'amqp://user:password@rabbit'

  rabbit:
    image: rabbitmq:3-management-alpine
    hostname: my-rabbit
    expose:
      - "5672"
      - "15671"
      - "15672"
      - "15691"
      - "15692"
      - "25672"
      - "4369"
      - "5671"
    environment:
      RABBITMQ_DEFAULT_USER : user
      RABBITMQ_DEFAULT_PASS : password

  # Internal services
  mongo:
    image: mongo
    expose:
      - "27017"

  htcondor:
    image:
      steven0414/htcondor
    volumes:
      - uchuva:/app
    expose:
      - "10389"
      - "22"
      - "9618"

### docker run -d -h docker -p 10022:22 --name openlava carlochess/openlava
  openlava:
    image:
      steven0414/openlava
    hostname: docker
    volumes:
      - uchuva:/app
    expose:
      - "22"

### docker run -d -h docker -p 10022:22 --privileged --name torque agaveapi/torque
  torque:
    image:
      agaveapi/torque
    volumes:
      - uchuva:/app
    hostname: docker
    expose:
      - "22"
      - "10389"
      - "9618"
    privileged: true

#### Recordar el sed del /etc/hosts
#### docker run -h docker.example.com -p 10022:22 --rm --name slurm agaveapi/slurm
  slurm:
    image:
      agaveapi/slurm
    volumes:
      - uchuva:/app
    hostname: docker.example.com
    expose:
      - "22"
      - "10389"
      - "6817"
      - "6818"

#docker run -p 4569:4569 --name my_s3 -d lphoward/fake-s3
#  fake-s3:
#    image:
#      lphoward/fake-s3

# docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it -v $(pwd)/docker/filebeat/uchuva.conf:/etc/logstash/conf.d/uchuva.conf --name elk sebp/elk
# 5601 (Kibana web interface).
# 9200 (Elasticsearch JSON interface).
# 5044 (Logstash Beats interface, receives logs from Beats such as Filebeat – see the Forwarding logs with Filebeat section).
#  elk:
#    image:
#      sebp/elk
#    volumes_from:
#      - uchuva
#    volumes:
#      - ./docker/filebeat/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf
#    ports:
#      - "5601:5601"

# docker run -d --volumes-from uchuva -v "./docker/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml" olinicola/filebeat
  filebeat:
    image:
      prima/filebeat
    volumes:
      - uchuva:/app
      - ./docker/filebeat/filebeat.yml:/filebeat.yml

# Persistent volumes
volumes:
  uchuva:
