apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: filebeat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: filebeat
    spec:
      containers:
      - image: steven0414/filebeat
        imagePullPolicy: ""
        name: filebeat
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: uchuva
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: uchuva
        persistentVolumeClaim:
          claimName: uchuva
status: {}
