apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: torque
  name: torque
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: torque
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: torque
    spec:
      containers:
      - image: agaveapi/torque
        imagePullPolicy: ""
        name: torque
        ports:
        - containerPort: 22
        - containerPort: 10389
        - containerPort: 9618
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /app
          name: uchuva
      hostname: docker
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: uchuva
        persistentVolumeClaim:
          claimName: uchuva
status: {}
